abstract: Perl interface for Google calculator
author: Daisuke Murase <typester@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WWW-Google-Calculator
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  HTML::TokeParser: 0
  WWW::Mechanize: 0
version: 0.04
